import { Titillium_Web } from 'next/font/google';
import './globals.css';

const titillium = Titillium_Web({ 
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Nur Shafa Salsabila || portofolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.ico"></link> 
      </head>
      <body className={titillium.className}>{children}</body>
    </html>
  );
}
